### ISSUE TITLE
setup STA Wifi

### ISSUE THREAD

**Issue by IndrawanBudiP** [zivillian/esp32-modbus-gateway#11]
I got an problem, after I build and also upload the program at the board. My board is not connect at the wifi, I try to find the wifi configuration in your program but I didnt find it. please help

**Comment by zivillian** [comment]
Your board should open a WIFI AP (named `ESP-...`) which will allow you to select your WiFi and enter the credentials.

**Comment by IndrawanBudiP** [comment]
thanks its work bro ! great job
