### ISSUE TITLE
Lot of errors using with ioBroker and LWPM410 Modbus RTU

### ISSUE THREAD

**Issue by christi-ko** [zivillian/esp32-modbus-gateway#6]
I am getting the following warning messages in iobroker. 

`
modbus.0 | 2022-09-20 16:45:15.004 | warn | Poll error count: 2 code: {"errorCode":131,"exceptionCode":229}
modbus.0 | 2022-09-20 16:45:13.136 | warn | Poll error count: 1 code: {"errorCode":132,"exceptionCode":226}
`
Is there something i can to to reduce the amount of error messages i receive?

**Comment by zivillian** [comment]
should be fixed with https://github.com/eModbus/eModbus/issues/268
